server:
  port: 8094
spring:
  application:
    name: service-autodeliver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
      # Sentinel Nacos数据源配置，Nacos中的规则会自动同步到sentinel流控规则中
      datasource:
        # 自定义的流控规则数据源名称
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-flow-rules
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow  # 类型来自RuleType类
        # 自定义的降级规则数据源名称
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-degrade-rules
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: degrade  # 类型来自RuleType类

logging:
  level:
    org.apache.ibatis: ${LOGGING_LEVEL:debug}
    com.github.thestyleofme: ${LOGGING_LEVEL:debug}
    com.alibaba.cloud: ${LOGGING_LEVEL:debug}

# 暴露spring boot健康检查等端点接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 总是暴露健康检查接口细节
  # http://localhost:8090/actuator/health
  endpoint:
    health:
      show-details: always

# 针对的被调用方微服务名称,不加就是全局生效
service-resume:
  ribbon:
    # 请求连接超时时间
    ConnectTimeout: 3000
    ##########################################Feign超时时长设置
    # 请求处理超时时间 即客户端读取超时时间，超时时间要小于Hystrix的超时时间，否则重试机制就无意义了
    ReadTimeout: 15000
    # 对所有操作都进行重试
    # 访问实例失败(超时)，允许自动重试，设置重试次数，失败后会更换实例访问
    # 请一定确保接口的幂等性，否则重试可能导致数据异常。
    OkToRetryOnAllOperations: true
    ####根据如上配置，当访问到故障请求的时候，它会再尝试访问一次当前实例（次数由MaxAutoRetries配置），
    ####如果不行，就换一个实例进行访问，如果还不行，再换一次实例访问（更换次数由MaxAutoRetriesNextServer配置），
    ####如果依然不行，返回失败信息。
    MaxAutoRetries: 0 #对当前选中实例重试次数，不包括第一次调用
    MaxAutoRetriesNextServer: 0 #切换实例的重试次数
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #负载策略调整
