server:
  port: 8762
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eurekaServerB
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://eurekaServerA:8761/eureka
    register-with-eureka: true
    fetch-registry: true

