server:
  port: 8091
spring:
  application:
    name: service-autodeliver
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
  client:
    service-url:
      # 注册到集群，就把多个Eureka server地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      defaultZone: http://eurekaServerA:8761/eureka,http://eurekaServerB:8762/eureka
    registry-fetch-interval-seconds: 10

# 针对的被调用方微服务名称,不加就是全局生效
#service-resume:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

logging:
  level:
    org.apache.ibatis: ${LOGGING_LEVEL:debug}
    com.github.thestyleofme: ${LOGGING_LEVEL:debug}

# 暴露spring boot健康检查等端点接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 总是暴露健康检查接口细节
  # http://localhost:8090/actuator/health
  endpoint:
    health:
      show-details: always

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 熔断超时设置，默认为1s
            timeoutInMilliseconds: 2000