server:
  port: 9002
spring:
  application:
    name: service-gateway
  zipkin:
    base-url: http://localhost:9411
    enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      routes:
        - id: oauth
          uri: lb://service-oauth2
          predicates:
            - Path=/oauth/**
          filters:
            - StripPrefix=1
        - id: adlr
          uri: lb://service-autodeliver
          predicates:
            - Path=/adlr/**
          filters:
            - StripPrefix=1
        - id: resm
          uri: lb://service-resume
          predicates:
            - Path=/resm/**
          filters:
            - StripPrefix=1


eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
  client:
    service-url:
      # 注册到集群，就把多个Eureka server地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      defaultZone: http://eurekaServerA:8761/eureka,http://eurekaServerB:8762/eureka
    registry-fetch-interval-seconds: 10

logging:
  level:
    com.github.thestyleofme: ${LOGGING_LEVEL:debug}
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug

# 暴露spring boot健康检查等端点接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 总是暴露健康检查接口细节
  # http://localhost:8090/actuator/health
  endpoint:
    health:
      show-details: always
