server:
  port: 9002
spring:
  application:
    name: service-gateway
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      routes: # 路由可以有多个
        - id: adlr # 我们自定义的路由ID，保持唯一
          #uri: http://127.0.0.1:8092  # 目标服务地址  自动投递微服务（部署多实例）
          # 动态路由：uri配置的应该是一个服务名称，而不应该是一个具体的服务实例的地址
          # gateway网关从服务注册中心获取实例信息然后负载后路由
          uri: lb://service-autodeliver
          # 断言：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。
          # 该接口包含多种默认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
          predicates:
            - Path=/adlr/**
          filters:
            - StripPrefix=1
        - id: resm     # 我们自定义的路由ID，保持唯一
          #uri: http://127.0.0.1:8081       # 目标服务地址
          uri: lb://service-resume
          predicates:
            - Path=/resm/**
          filters:
            # http://localhost:9002/resm/resume/openstate/1545132
            - StripPrefix=1 # 去掉前缀 1代表去掉1个 2代表去掉2个


eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
  client:
    service-url:
      # 注册到集群，就把多个Eureka server地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      defaultZone: http://eurekaServerA:8761/eureka,http://eurekaServerB:8762/eureka
    registry-fetch-interval-seconds: 10

logging:
  level:
    com.github.thestyleofme: ${LOGGING_LEVEL:debug}
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug

# 暴露spring boot健康检查等端点接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 总是暴露健康检查接口细节
  # http://localhost:8090/actuator/health
  endpoint:
    health:
      show-details: always
