server:
  port: 9999
spring:
  application:
    name: service-oauth2
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_explore?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: tse@9527
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 30
      maxWait: 50000
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
  client:
    service-url:
      # 注册到集群，就把多个Eureka server地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      defaultZone: http://eurekaServerA:8761/eureka,http://eurekaServerB:8762/eureka
    registry-fetch-interval-seconds: 10

logging:
  level:
    org.apache.ibatis: ${LOGGING_LEVEL:debug}
    com.github.thestyleofme: ${LOGGING_LEVEL:debug}
    org.springframework.web: ${LOG_LEVEL:info}
